### ISSUE TITLE
Responsive display

### ISSUE THREAD

**Issue by TamerElMorsi** [jsanahuja/jquery.instagramFeed#66]
consider those setting for desktop display
note that i only want to display 10 images on one row
'items': 10,
'items_per_row': 10,

when i switch to mobile the images get smaller and not visible enough
so how to tell the browser in case of mobile to display one or two items per row

**Comment by RosalieWessels** [comment]
I had the exact same problem. What I did to solve it was using Javascript to check the screen size of the screen. If the screen size was less than 850 pixels (about phone size), I set items per row to 2 (showing two items per row). Otherwise, I show 4 items per row. Then, when defining the InstagramFeed you set items_per_row to the variable you created. This allowed me to have a certain number of items per row based on screen size. I hope that helped you.
```
var screenWidth = screen.width
console.log("Screen width", screenWidth)
if (screenWidth <= 850){
     items_per_row = 2
}
else {
     items_per_row = 4
}
```
